### ISSUE TITLE
Improve performance by some little optimizations

### ISSUE THREAD

**Issue by foosmate** [amsa-code/risky#71]
I just have a short review under the hood of your Risky/AIS parser as a fantastic source for RxJava examples. Thank you so much for this great pool of ideas.

Here is some feedback, how you can make the AIS parsing much faster:

1. Many methods are larger than 325 bytes (ByteBode), which prevent Hotspot from inlining these methods (even if they are running super hot). This is a tremendous performance penalty. For instance ```Streams#TO_FIX``` lambda is 423 bytes long (ByteCode) which means that this will *never* be inlined. You can simply fix that by splitting this methods in sub-methods each smaller than 325 bytes. For quick checking run a benchmark with these arguments and check all methods that are logged with "hot method too big": ```-XX:+PrintCompilation -XX:+UnlockDiagnosticVMOptions -XX:+PrintInlining```
2. There is some locking and synchronizing under the hood which disable a lot of optimization possibilities that Hotspot can not apply anymore (code reordering etc.).  It’s much better to perform locking outside (depending on the use case) to allow single-threaded applications to run as fast as possible. For instance ```AisExtractor#getValue(int,int)``` has a performance penalty which only is needed under concurrent conditions.
4. There are some ```for``` loops with unneccessary expensive conditions, that could be improved for performance. 
For instance …
   ` for (int i = strFrom; i < Math.min(strTo, slen); i++) { … }`
could be written like this …
    `for (int i = strFrom, j = Math.min(strTo, slen); i < j; i++) { ... }`

Don’t get me wrong, this AIS library is incredible fast (and smart :-), but could be faster with very little effort.

Thanks for the great work!

PS: Having an eye on point 1 will have the most positive impact on performance.

**Comment by davidmoten** [comment]
Thanks @Foosmate. I'll check the status of our jvm benchmark code so that we can measure the effects of these ideas.
1. Will be interesting to see
2. I'll have a look, I agree very helpful to minimize synchronization/locking
3. Definitely looks good to fix

**Comment by davidmoten** [comment]
Re 3:
>There are some for loops with unneccessary expensive conditions, that could be improved for performance.

I only spotted the one example that you mentioned in the ais project after grepping for "for" and "while".

Benchmarks are below and interestingly enough perf is worse post-change (~4% less throughput) so I'll probably just add a comment to the code that it's been investigated.

Baseline:
```
Benchmark                                                          Mode  Cnt       Score      Error  Units
BenchmarksAis.parseAisPositionANmeaMessage                        thrpt   10  677101.958 ± 3831.039  ops/s
BenchmarksAis.parseAisPositionBNmeaMessage                        thrpt   10  656759.594 ± 1534.609  ops/s
BenchmarksAis.parseMany                                           thrpt   10      12.482 ±    0.221  ops/s
BenchmarksAis.parseShipStaticNmeaMessage                          thrpt   10  658444.936 ± 2892.954  ops/s
BenchmarksAis.parseShipStaticNmeaMessageAndExtractBitsOfInterest  thrpt   10  424420.770 ± 2167.800  ops/s
```
Post-change:
```
Benchmark                                                          Mode  Cnt       Score       Error  Units
BenchmarksAis.parseAisPositionANmeaMessage                        thrpt   10  649205.394 ±  3349.068  ops/s
BenchmarksAis.parseAisPositionBNmeaMessage                        thrpt   10  649711.811 ±  2790.866  ops/s
BenchmarksAis.parseMany                                           thrpt   10      12.446 ±     0.048  ops/s
BenchmarksAis.parseShipStaticNmeaMessage                          thrpt   10  629193.365 ± 11238.941  ops/s
BenchmarksAis.parseShipStaticNmeaMessageAndExtractBitsOfInterest  thrpt   10  420715.230 ±  1382.865  ops/s
```

**Comment by davidmoten** [comment]
Re 2: 
> locking and synchronizing in AisExtractor methods

This is a good catch, the sychronization was left over from when fields were calculated lazily. This is no longer the case so I've gotten rid of them. 

Performance effects compared to the baseline are a little bit up and down but I'll definitely include this change.

```
Benchmark                                                          Mode  Cnt       Score       Error  Units
BenchmarksAis.parseAisPositionANmeaMessage                        thrpt   10  691525.895 ±  1345.949  ops/s
BenchmarksAis.parseAisPositionBNmeaMessage                        thrpt   10  675190.308 ±  2512.144  ops/s
BenchmarksAis.parseMany                                           thrpt   10      12.113 ±     0.157  ops/s
BenchmarksAis.parseShipStaticNmeaMessage                          thrpt   10  660379.368 ±  5125.607  ops/s
BenchmarksAis.parseShipStaticNmeaMessageAndExtractBitsOfInterest  thrpt   10  419468.768 ± 20127.775  ops/s
```

**Comment by davidmoten** [comment]
Re 1:

>inlining

So the benefits of inlining can only be demonstrated in benchmarks. To this end I added another benchmark method that converts a list of 44K NMEA lines to Fix objects via the Streams.TO_FIX function.

Without modification the new benchmark gives:

```
Benchmark                      Mode  Cnt  Score   Error  Units
BenchmarksAis.parseManyFixes  thrpt   10  2.659 ± 0.039  ops/s
```

With modification (commit ce37f018 which splits TO_FIX into methods to improve inlining) the new benchmark gives:

```
Benchmark                      Mode  Cnt  Score   Error  Units
BenchmarksAis.parseManyFixes  thrpt   10  2.439 ± 0.165  ops/s
```

Following the suggested course of action reduces throughput by 8%. Unfortunately the statement "This is a tremendous performance penalty" turns out not to be the case at all. Perf is a complex business so I'm not surprised really.

Consequently I won't split up TO_FIX method as suggested.

@Foosmate if you have any other suggestion that you'd like to try please do. Benchmarks are run like this:

```
cd ais
mvn clean install -P benchmark
```

**Comment by davidmoten** [comment]
I've addressed everything for the moment so I'll close. Reopen if you'd like to keep discussing this one.

**Comment by Foosmate** [comment]
As mentioned, I only did a code review (looking for great RxJava examples) and did not run any benchmarks myself. 

In particular, one thing surprises and fascinates me likewise: Basically, the only time where inlining doesn't have much of an effect is when the algorithmic / processing part significantly outweighs the number of calls when the method is running hot. But this is rather not to be expected in a parsing scenario like this. 

I would like to take a closer look to the processing part in the next few days to see why there is even a performance degradation here. We have recently been able to achieve a performance increase of a factor of 2-3x in a binary parsing library by eliminating all the inlining preventions.

Thank you very much for this clean analysis.

**Comment by davidmoten** [comment]
Yeah interesting to see what works and what doesn't. Keep looking of course, would be great to find significant improvements in the parsing.

**Comment by Foosmate** [comment]
I looked into the code again (over a new cup of a fantastic espresso blend, btw ;-).

Inlining does not have a noticeable effect here, because the complex processing (parsing) and garbage collecting takes too much time and the method invocation cost is completely pushed into the background.

The fastest way of consuming AIS messages would probably be a no-garbage parser that doesn't use Strings and produce no short-living objects at all. In this case, even during a complex parsing job, the GC would not kick in once. However, this is conceptually difficult and somekind inconvenient to implement. 

If you want to optimize even further, then it probably makes the most sense to look specifically at individual aspects that are easy to realize. In particular, you could try to reduce the number of short-living objects to ease the job of the GC a little.

Maybe it's worth to consistently eliminate some (unnecessary) String concatenations?

FixImpl:45 -> `Preconditions.checkArgument(courseOverGroundDegrees.get() < 360 && courseOverGroundDegrees.get() >= 0, "cog=" + courseOverGroundDegrees.get());`

Also it may have a significant effect if some StringBuilders can be re-used (as instance field, in a pool or even as ThreadLocal). NmeaUtil seems to have quite a few one under heavy load.

I also looked at the Flame graph in the profiler and a lot of time is spent in String processing (as expected) but there are a few surprising places as well. For instance, there is some time spent in exception processing, like non existing constants on `Enum#valueOf()` which is "handled" by catching a `RuntimeException` in NmeaUtil:231. 

Maybe, it would be worth to generate a char-based lookup tree for such cases to prevent HashMap from doing this job.

**Comment by davidmoten** [comment]
See #75 which has a big impact on throughput for my company's AIS feed and was due to an exception being used for normal flow control (much too heavy on allocation).

**Comment by Foosmate** [comment]
Looks like you found several points that resulted in a significant throughput improvement. That's great ...
:-)

**Comment by davidmoten** [comment]
Rewrote splitBy (again) to reduce allocations ([8903ce1](https://github.com/amsa-code/risky/commit/8903ce1b8b61fc850ffa8ac6d77c23784cf44149)).

```
Benchmark                                        Mode  Cnt    Score   Error  Units
BenchmarksDecodeManyNmea.parseManyFixesShorter  thrpt   10  330.131 ± 0.549  ops/s
BenchmarksDecodeManyNmea.parseManyNmeaMessage   thrpt   10   31.435 ± 0.533  ops/s
```

**Comment by davidmoten** [comment]
Customized parseInt and parseLong (decimal focused, digits only) [85dd5e6](https://github.com/amsa-code/risky/commit/85dd5e65a27722473268034f6a965ddd5195bf93).
```
Benchmark                                        Mode  Cnt    Score   Error  Units
BenchmarksDecodeManyNmea.parseManyFixesShorter  thrpt   10  338.133 ± 3.204  ops/s
BenchmarksDecodeManyNmea.parseManyNmeaMessage   thrpt   10   30.916 ± 0.734  ops/s

```

**Comment by davidmoten** [comment]
Looks like we are done for the moment, I'll close. Thanks @foosmate!
